import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Victor's Gym Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <nav>
          <Link href="/">Journal</Link>
          <Link href="/workouts">Workouts</Link>
          <Link href="/stats">Stats</Link>
          <Link href="/settings">Settings</Link>
        </nav>
      </body>
    </html>
  );
}
